/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { GenerateDocumentPreviewRequestType } from "../../types/GenerateDocumentPreviewRequestType";
import { GenerateDocumentPreviewRequestFormatOpts } from "../../types/GenerateDocumentPreviewRequestFormatOpts";

export const GenerateDocumentPreviewRequest: core.serialization.Schema<
    serializers.GenerateDocumentPreviewRequest.Raw,
    Omit<PogodocApi.GenerateDocumentPreviewRequest, "templateId">
> = core.serialization.object({
    type: GenerateDocumentPreviewRequestType,
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    formatOpts: GenerateDocumentPreviewRequestFormatOpts.optional(),
});

export declare namespace GenerateDocumentPreviewRequest {
    export interface Raw {
        type: GenerateDocumentPreviewRequestType.Raw;
        data: Record<string, unknown>;
        formatOpts?: GenerateDocumentPreviewRequestFormatOpts.Raw | null;
    }
}
