/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { GenerateTemplatePreviewsRequestType } from "../../types/GenerateTemplatePreviewsRequestType";
import { GenerateTemplatePreviewsRequestFormatOpts } from "../../types/GenerateTemplatePreviewsRequestFormatOpts";

export const GenerateTemplatePreviewsRequest: core.serialization.Schema<
    serializers.GenerateTemplatePreviewsRequest.Raw,
    PogodocApi.GenerateTemplatePreviewsRequest
> = core.serialization.object({
    type: GenerateTemplatePreviewsRequestType,
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    formatOpts: GenerateTemplatePreviewsRequestFormatOpts.optional(),
});

export declare namespace GenerateTemplatePreviewsRequest {
    export interface Raw {
        type: GenerateTemplatePreviewsRequestType.Raw;
        data: Record<string, unknown>;
        formatOpts?: GenerateTemplatePreviewsRequestFormatOpts.Raw | null;
    }
}
