/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { SaveCreatedTemplateRequestTemplateInfo } from "../../types/SaveCreatedTemplateRequestTemplateInfo";
import { SaveCreatedTemplateRequestPreviewIds } from "../../types/SaveCreatedTemplateRequestPreviewIds";

export const SaveCreatedTemplateRequest: core.serialization.Schema<
    serializers.SaveCreatedTemplateRequest.Raw,
    PogodocApi.SaveCreatedTemplateRequest
> = core.serialization.object({
    templateInfo: SaveCreatedTemplateRequestTemplateInfo,
    previewIds: SaveCreatedTemplateRequestPreviewIds,
});

export declare namespace SaveCreatedTemplateRequest {
    export interface Raw {
        templateInfo: SaveCreatedTemplateRequestTemplateInfo.Raw;
        previewIds: SaveCreatedTemplateRequestPreviewIds.Raw;
    }
}
