/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { UpdateTemplateRequestTemplateInfo } from "../../types/UpdateTemplateRequestTemplateInfo";
import { UpdateTemplateRequestPreviewIds } from "../../types/UpdateTemplateRequestPreviewIds";

export const UpdateTemplateRequest: core.serialization.Schema<
    serializers.UpdateTemplateRequest.Raw,
    PogodocApi.UpdateTemplateRequest
> = core.serialization.object({
    templateInfo: UpdateTemplateRequestTemplateInfo,
    previewIds: UpdateTemplateRequestPreviewIds,
    contentId: core.serialization.string(),
});

export declare namespace UpdateTemplateRequest {
    export interface Raw {
        templateInfo: UpdateTemplateRequestTemplateInfo.Raw;
        previewIds: UpdateTemplateRequestPreviewIds.Raw;
        contentId: string;
    }
}
