/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const UploadTemplateIndexHtmlRequest: core.serialization.Schema<
    serializers.UploadTemplateIndexHtmlRequest.Raw,
    PogodocApi.UploadTemplateIndexHtmlRequest
> = core.serialization.object({
    templateIndex: core.serialization.string(),
});

export declare namespace UploadTemplateIndexHtmlRequest {
    export interface Raw {
        templateIndex: string;
    }
}
