/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index";

/**
 * @example
 *     {
 *         type: "docx",
 *         target: "pdf"
 *     }
 */
export interface InitializeRenderJobRequest {
    data?: Record<string, unknown>;
    type: PogodocApi.InitializeRenderJobRequestType;
    target: PogodocApi.InitializeRenderJobRequestTarget;
    templateId?: string;
    formatOpts?: PogodocApi.InitializeRenderJobRequestFormatOpts;
}
