/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         type: "docx",
 *         target: "pdf"
 *     }
 */
export interface InitializeRenderJobRequest {
    /** Sample data for the template */
    data?: Record<string, unknown>;
    /** Type of template to be rendered */
    type: InitializeRenderJobRequest.Type;
    /** Type of output to be rendered */
    target: InitializeRenderJobRequest.Target;
    /** ID of the template to be used */
    templateId?: string;
    /** Format options for the rendered document */
    formatOpts?: InitializeRenderJobRequest.FormatOpts;
}

export namespace InitializeRenderJobRequest {
    /**
     * Type of template to be rendered
     */
    export type Type = "docx" | "xlsx" | "pptx" | "ejs" | "html" | "latex" | "react";
    export const Type = {
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Ejs: "ejs",
        Html: "html",
        Latex: "latex",
        React: "react",
    } as const;
    /**
     * Type of output to be rendered
     */
    export type Target = "pdf" | "html" | "docx" | "xlsx" | "pptx" | "png" | "jpg";
    export const Target = {
        Pdf: "pdf",
        Html: "html",
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Png: "png",
        Jpg: "jpg",
    } as const;

    /**
     * Format options for the rendered document
     */
    export interface FormatOpts {
        fromPage?: number;
        toPage?: number;
        format?: FormatOpts.Format;
        /** Selector to wait for to know when the page is loaded and can be saved as pdf, png, etc. */
        waitForSelector?: string;
    }

    export namespace FormatOpts {
        export type Format = "letter" | "legal" | "tabloid" | "ledger" | "a0" | "a1" | "a2" | "a3" | "a4" | "a5" | "a6";
        export const Format = {
            Letter: "letter",
            Legal: "legal",
            Tabloid: "tabloid",
            Ledger: "ledger",
            A0: "a0",
            A1: "a1",
            A2: "a2",
            A3: "a3",
            A4: "a4",
            A5: "a5",
            A6: "a6",
        } as const;
    }
}
