/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetJobStatusResponse {
    type: GetJobStatusResponse.Type;
    jobId: string;
    target: GetJobStatusResponse.Target;
    output?: GetJobStatusResponse.Output;
    success?: boolean;
    status?: string;
}

export namespace GetJobStatusResponse {
    export type Type = "docx" | "xlsx" | "pptx" | "ejs" | "html" | "latex" | "react";
    export const Type = {
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Ejs: "ejs",
        Html: "html",
        Latex: "latex",
        React: "react",
    } as const;
    export type Target = "pdf" | "html" | "docx" | "xlsx" | "pptx" | "png" | "jpg";
    export const Target = {
        Pdf: "pdf",
        Html: "html",
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Png: "png",
        Jpg: "jpg",
    } as const;

    export interface Output {
        data: Output.Data;
        metadata: Output.Metadata;
    }

    export namespace Output {
        export interface Data {
            url: string;
        }

        export interface Metadata {
            renderTime: number;
        }
    }
}
