/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InitializeRenderJobResponse {
    jobId: string;
    target: InitializeRenderJobResponse.Target;
    presignedDataUploadUrl?: string;
    presignedTemplateUploadUrl?: string;
}

export namespace InitializeRenderJobResponse {
    export type Target = "pdf" | "html" | "docx" | "xlsx" | "pptx" | "png" | "jpg";
    export const Target = {
        Pdf: "pdf",
        Html: "html",
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Png: "png",
        Jpg: "jpg",
    } as const;
}
