/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface InitializeRenderJobResponse {
    jobId: string;
    target: PogodocApi.InitializeRenderJobResponseTarget;
    presignedDataUploadUrl?: string;
    presignedTemplateUploadUrl?: string;
}
