/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const GenerateDocumentPreviewResponse: core.serialization.ObjectSchema<
    serializers.GenerateDocumentPreviewResponse.Raw,
    PogodocApi.GenerateDocumentPreviewResponse
> = core.serialization.object({
    url: core.serialization.string().optional(),
    jobId: core.serialization.string(),
});

export declare namespace GenerateDocumentPreviewResponse {
    export interface Raw {
        url?: string | null;
        jobId: string;
    }
}
