/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetJobStatusResponseOutputData: core.serialization.ObjectSchema<
    serializers.GetJobStatusResponseOutputData.Raw,
    PogodocApi.GetJobStatusResponseOutputData
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace GetJobStatusResponseOutputData {
    export interface Raw {
        url: string;
    }
}
