/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { InitializeRenderJobResponseTarget } from "./InitializeRenderJobResponseTarget";

export const InitializeRenderJobResponse: core.serialization.ObjectSchema<
    serializers.InitializeRenderJobResponse.Raw,
    PogodocApi.InitializeRenderJobResponse
> = core.serialization.object({
    jobId: core.serialization.string(),
    target: InitializeRenderJobResponseTarget,
    presignedDataUploadUrl: core.serialization.string().optional(),
    presignedTemplateUploadUrl: core.serialization.string().optional(),
});

export declare namespace InitializeRenderJobResponse {
    export interface Raw {
        jobId: string;
        target: InitializeRenderJobResponseTarget.Raw;
        presignedDataUploadUrl?: string | null;
        presignedTemplateUploadUrl?: string | null;
    }
}
