/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SaveCreatedTemplateRequestTemplateInfoCategoriesItem = "invoice" | "mail" | "report" | "cv" | "other";
export const SaveCreatedTemplateRequestTemplateInfoCategoriesItem = {
    Invoice: "invoice",
    Mail: "mail",
    Report: "report",
    Cv: "cv",
    Other: "other",
} as const;
