/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const StartRenderJobRequest: core.serialization.Schema<
    serializers.StartRenderJobRequest.Raw,
    PogodocApi.StartRenderJobRequest
> = core.serialization.object({
    shouldWaitForRenderCompletion: core.serialization.boolean().optional(),
    uploadPresignedS3Url: core.serialization.string().optional(),
});

export declare namespace StartRenderJobRequest {
    export interface Raw {
        shouldWaitForRenderCompletion?: boolean | null;
        uploadPresignedS3Url?: string | null;
    }
}
