/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { ExtractTemplateFilesRequest } from "../types/ExtractTemplateFilesRequest";

export const Request: core.serialization.Schema<
    serializers.templates.extractTemplateFiles.Request.Raw,
    PogodocApi.ExtractTemplateFilesRequest | undefined
> = ExtractTemplateFilesRequest.optional();

export declare namespace Request {
    export type Raw = ExtractTemplateFilesRequest.Raw | null | undefined;
}
