/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index";

/**
 * @example
 *     {
 *         type: "docx",
 *         data: {
 *             "key": "value"
 *         }
 *     }
 */
export interface GenerateTemplatePreviewsRequest {
    type: PogodocApi.GenerateTemplatePreviewsRequestType;
    data: Record<string, unknown>;
    formatOpts?: PogodocApi.GenerateTemplatePreviewsRequestFormatOpts;
}
