/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index";

/**
 * @example
 *     {
 *         templateInfo: {
 *             title: "title",
 *             description: "description",
 *             type: "docx",
 *             sampleData: {
 *                 "key": "value"
 *             },
 *             categories: ["invoice"]
 *         },
 *         previewIds: {
 *             pngJobId: "pngJobId",
 *             pdfJobId: "pdfJobId"
 *         }
 *     }
 */
export interface SaveCreatedTemplateRequest {
    templateInfo: PogodocApi.SaveCreatedTemplateRequestTemplateInfo;
    previewIds: PogodocApi.SaveCreatedTemplateRequestPreviewIds;
}
