/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index";

/**
 * @example
 *     {
 *         templateInfo: {
 *             title: "title",
 *             description: "description",
 *             type: "docx",
 *             sampleData: {
 *                 "key": "value"
 *             },
 *             categories: ["invoice"]
 *         },
 *         previewIds: {
 *             pngJobId: "pngJobId",
 *             pdfJobId: "pdfJobId"
 *         },
 *         contentId: "contentId"
 *     }
 */
export interface UpdateTemplateRequest {
    templateInfo: PogodocApi.UpdateTemplateRequestTemplateInfo;
    previewIds: PogodocApi.UpdateTemplateRequestPreviewIds;
    contentId: string;
}
