/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         templateIndex: "templateIndex"
 *     }
 */
export interface UploadTemplateIndexHtmlRequest {
    templateIndex: string;
}
