/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface GenerateTemplatePreviewsRequestFormatOpts {
    fromPage?: number;
    toPage?: number;
    format?: PogodocApi.GenerateTemplatePreviewsRequestFormatOptsFormat;
    waitForSelector?: string;
}
