/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface GenerateTemplatePreviewsResponse {
    pngPreview: PogodocApi.GenerateTemplatePreviewsResponsePngPreview;
    pdfPreview: PogodocApi.GenerateTemplatePreviewsResponsePdfPreview;
}
