/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SaveCreatedTemplateRequestTemplateInfoType = "docx" | "xlsx" | "pptx" | "ejs" | "html" | "latex" | "react";
export const SaveCreatedTemplateRequestTemplateInfoType = {
    Docx: "docx",
    Xlsx: "xlsx",
    Pptx: "pptx",
    Ejs: "ejs",
    Html: "html",
    Latex: "latex",
    React: "react",
} as const;
