/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface UpdateTemplateRequestTemplateInfo {
    title: string;
    description: string;
    type: PogodocApi.UpdateTemplateRequestTemplateInfoType;
    sampleData: Record<string, unknown>;
    sourceCode?: string;
    categories: PogodocApi.UpdateTemplateRequestTemplateInfoCategoriesItem[];
}
