/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const CloneTemplateResponse: core.serialization.ObjectSchema<
    serializers.CloneTemplateResponse.Raw,
    PogodocApi.CloneTemplateResponse
> = core.serialization.object({
    newTemplateId: core.serialization.string(),
});

export declare namespace CloneTemplateResponse {
    export interface Raw {
        newTemplateId: string;
    }
}
