/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const ExtractTemplateFilesRequest: core.serialization.ObjectSchema<
    serializers.ExtractTemplateFilesRequest.Raw,
    PogodocApi.ExtractTemplateFilesRequest
> = core.serialization.object({});

export declare namespace ExtractTemplateFilesRequest {
    export interface Raw {}
}
