/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { GenerateTemplatePreviewsResponsePngPreview } from "./GenerateTemplatePreviewsResponsePngPreview";
import { GenerateTemplatePreviewsResponsePdfPreview } from "./GenerateTemplatePreviewsResponsePdfPreview";

export const GenerateTemplatePreviewsResponse: core.serialization.ObjectSchema<
    serializers.GenerateTemplatePreviewsResponse.Raw,
    PogodocApi.GenerateTemplatePreviewsResponse
> = core.serialization.object({
    pngPreview: GenerateTemplatePreviewsResponsePngPreview,
    pdfPreview: GenerateTemplatePreviewsResponsePdfPreview,
});

export declare namespace GenerateTemplatePreviewsResponse {
    export interface Raw {
        pngPreview: GenerateTemplatePreviewsResponsePngPreview.Raw;
        pdfPreview: GenerateTemplatePreviewsResponsePdfPreview.Raw;
    }
}
