/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const InitializeTemplateCreationResponse: core.serialization.ObjectSchema<
    serializers.InitializeTemplateCreationResponse.Raw,
    PogodocApi.InitializeTemplateCreationResponse
> = core.serialization.object({
    jobId: core.serialization.string(),
    presignedTemplateUploadUrl: core.serialization.string(),
});

export declare namespace InitializeTemplateCreationResponse {
    export interface Raw {
        jobId: string;
        presignedTemplateUploadUrl: string;
    }
}
