/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateTemplateRequestPreviewIds: core.serialization.ObjectSchema<
    serializers.UpdateTemplateRequestPreviewIds.Raw,
    PogodocApi.UpdateTemplateRequestPreviewIds
> = core.serialization.object({
    pngJobId: core.serialization.string(),
    pdfJobId: core.serialization.string(),
});

export declare namespace UpdateTemplateRequestPreviewIds {
    export interface Raw {
        pngJobId: string;
        pdfJobId: string;
    }
}
