/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetTemplateByIdResponse {
    /** Unique ID of the template */
    uuid: string;
    /** Title of the template */
    title: string;
    /** Description of the template */
    description?: string;
    /** Type of template to be rendered */
    type: GetTemplateByIdResponse.Type;
    /** Categories of the template */
    categories: string[];
    /** Permissions of the template */
    permissions: GetTemplateByIdResponse.Permissions;
    /** Preview URL of the template */
    preview?: string;
    /** Content ID of the template in S3 */
    contentId: string;
    /** Source code of the template */
    sourceCode?: string;
    /** Sample data for the template */
    sampleData?: Record<string, unknown>;
}

export namespace GetTemplateByIdResponse {
    /**
     * Type of template to be rendered
     */
    export type Type = "docx" | "xlsx" | "pptx" | "ejs" | "html" | "latex" | "react";
    export const Type = {
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Ejs: "ejs",
        Html: "html",
        Latex: "latex",
        React: "react",
    } as const;
    /**
     * Permissions of the template
     */
    export type Permissions = "public" | "private";
    export const Permissions = {
        Public: "public",
        Private: "private",
    } as const;
}
