/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetUserTemplatesResponse {
    templates: GetUserTemplatesResponse.Templates.Item[];
}

export namespace GetUserTemplatesResponse {
    export type Templates = Templates.Item[];

    export namespace Templates {
        export interface Item {
            uuid: string;
            title: string;
            description?: string;
        }
    }
}
