/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetUserTemplatesRequestCategory =
    | "invoice"
    | "mail"
    | "report"
    | "cv"
    | "receipt"
    | "order"
    | "contract"
    | "certificate"
    | "statement"
    | "brochure"
    | "warranty"
    | "poster"
    | "menu"
    | "catalog"
    | "packaging"
    | "advertisement"
    | "other"
    | "favorite";
export const GetUserTemplatesRequestCategory = {
    Invoice: "invoice",
    Mail: "mail",
    Report: "report",
    Cv: "cv",
    Receipt: "receipt",
    Order: "order",
    Contract: "contract",
    Certificate: "certificate",
    Statement: "statement",
    Brochure: "brochure",
    Warranty: "warranty",
    Poster: "poster",
    Menu: "menu",
    Catalog: "catalog",
    Packaging: "packaging",
    Advertisement: "advertisement",
    Other: "other",
    Favorite: "favorite",
} as const;
