/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetUserTemplatesRequestSort =
    | "createdAt:desc"
    | "createdAt:asc"
    | "updatedAt:desc"
    | "updatedAt:asc"
    | "title:asc"
    | "title:desc";
export const GetUserTemplatesRequestSort = {
    CreatedAtDesc: "createdAt:desc",
    CreatedAtAsc: "createdAt:asc",
    UpdatedAtDesc: "updatedAt:desc",
    UpdatedAtAsc: "updatedAt:asc",
    TitleAsc: "title:asc",
    TitleDesc: "title:desc",
} as const;
