/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InitializeTemplateCreationResponse {
    /** ID of the template */
    templateId: string;
    /** Presigned URL to upload the template to S3 */
    presignedTemplateUploadUrl: string;
}
