/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { InitializeRenderJobRequestFormatOptsFormat } from "./InitializeRenderJobRequestFormatOptsFormat";

export const InitializeRenderJobRequestFormatOpts: core.serialization.ObjectSchema<
    serializers.InitializeRenderJobRequestFormatOpts.Raw,
    PogodocApi.InitializeRenderJobRequestFormatOpts
> = core.serialization.object({
    fromPage: core.serialization.number().optional(),
    toPage: core.serialization.number().optional(),
    format: InitializeRenderJobRequestFormatOptsFormat.optional(),
    waitForSelector: core.serialization.string().optional(),
});

export declare namespace InitializeRenderJobRequestFormatOpts {
    export interface Raw {
        fromPage?: number | null;
        toPage?: number | null;
        format?: InitializeRenderJobRequestFormatOptsFormat.Raw | null;
        waitForSelector?: string | null;
    }
}
