/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const StartImmediateRenderResponse: core.serialization.ObjectSchema<
    serializers.StartImmediateRenderResponse.Raw,
    PogodocApi.StartImmediateRenderResponse
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace StartImmediateRenderResponse {
    export interface Raw {
        url: string;
    }
}
