/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetJobStatusResponseType: core.serialization.Schema<
    serializers.GetJobStatusResponseType.Raw,
    PogodocApi.GetJobStatusResponseType
> = core.serialization.enum_(["docx", "xlsx", "pptx", "ejs", "html", "latex", "react"]);

export declare namespace GetJobStatusResponseType {
    export type Raw = "docx" | "xlsx" | "pptx" | "ejs" | "html" | "latex" | "react";
}
