/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetJobStatusResponseType } from "./GetJobStatusResponseType";
import { GetJobStatusResponseTarget } from "./GetJobStatusResponseTarget";
import { GetJobStatusResponseOutput } from "./GetJobStatusResponseOutput";

export const GetJobStatusResponse: core.serialization.ObjectSchema<
    serializers.GetJobStatusResponse.Raw,
    PogodocApi.GetJobStatusResponse
> = core.serialization.object({
    type: GetJobStatusResponseType,
    jobId: core.serialization.string(),
    target: GetJobStatusResponseTarget,
    output: GetJobStatusResponseOutput.optional(),
    success: core.serialization.boolean().optional(),
    status: core.serialization.string().optional(),
});

export declare namespace GetJobStatusResponse {
    export interface Raw {
        type: GetJobStatusResponseType.Raw;
        jobId: string;
        target: GetJobStatusResponseTarget.Raw;
        output?: GetJobStatusResponseOutput.Raw | null;
        success?: boolean | null;
        status?: string | null;
    }
}
