/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const InitializeRenderJobResponseTarget: core.serialization.Schema<
    serializers.InitializeRenderJobResponseTarget.Raw,
    PogodocApi.InitializeRenderJobResponseTarget
> = core.serialization.enum_(["pdf", "html", "docx", "xlsx", "pptx", "png", "jpg"]);

export declare namespace InitializeRenderJobResponseTarget {
    export type Raw = "pdf" | "html" | "docx" | "xlsx" | "pptx" | "png" | "jpg";
}
