/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const StartImmediateRenderRequestFormatOptsFormat: core.serialization.Schema<
    serializers.StartImmediateRenderRequestFormatOptsFormat.Raw,
    PogodocApi.StartImmediateRenderRequestFormatOptsFormat
> = core.serialization.enum_(["letter", "legal", "tabloid", "ledger", "a0", "a1", "a2", "a3", "a4", "a5", "a6"]);

export declare namespace StartImmediateRenderRequestFormatOptsFormat {
    export type Raw = "letter" | "legal" | "tabloid" | "ledger" | "a0" | "a1" | "a2" | "a3" | "a4" | "a5" | "a6";
}
