/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetJobStatusResponse {
    /** ID of the render job */
    jobId: string;
    /** ID of the template being used */
    templateId?: string;
    /** Target of the render job */
    target: string;
    /** Presigned URL to upload the rendered output to S3 */
    uploadPresignedS3Url?: string;
    /** Format options for the rendered document */
    formatOpts?: GetJobStatusResponse.FormatOpts;
    /** Status of the render job */
    status: string;
    /** Whether the render job was successful */
    success?: boolean;
    output?: GetJobStatusResponse.Output;
    /** Error that occurred during render */
    error?: string;
}

export namespace GetJobStatusResponse {
    /**
     * Format options for the rendered document
     */
    export interface FormatOpts {
        fromPage?: number;
        toPage?: number;
        format?: FormatOpts.Format;
        /** Selector to wait for to know when the page is loaded and can be saved as pdf, png, etc. */
        waitForSelector?: string;
    }

    export namespace FormatOpts {
        export type Format = "letter" | "legal" | "tabloid" | "ledger" | "a0" | "a1" | "a2" | "a3" | "a4" | "a5" | "a6";
        export const Format = {
            Letter: "letter",
            Legal: "legal",
            Tabloid: "tabloid",
            Ledger: "ledger",
            A0: "a0",
            A1: "a1",
            A2: "a2",
            A3: "a3",
            A4: "a4",
            A5: "a5",
            A6: "a6",
        } as const;
    }

    export interface Output {
        data: Output.Data;
        metadata: Output.Metadata;
    }

    export namespace Output {
        export interface Data {
            /** URL of the rendered output */
            url: string;
        }

        export interface Metadata {
            /** Time taken to render the output */
            renderTime: number;
        }
    }
}
