/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetJobStatusResponse {
    /** ID of the render job */
    jobId: string;
    /** Target of the render job */
    target: string;
    /** Status of the render job */
    status: string;
    /** Whether the render job was successful */
    success?: boolean;
    output?: GetJobStatusResponse.Output;
    /** Error that occurred during render */
    error?: string;
}

export namespace GetJobStatusResponse {
    export interface Output {
        data: Output.Data;
        metadata: Output.Metadata;
    }

    export namespace Output {
        export interface Data {
            /** URL of the rendered output */
            url: string;
        }

        export interface Metadata {
            /** Time taken to render the output */
            renderTime: number;
        }
    }
}
