/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface StartRenderJobResponse {
    /** ID of the render job */
    jobId: string;
    /** Type of output to be rendered */
    target?: StartRenderJobResponse.Target;
    /** Status of the render job */
    status?: string;
    /** Whether the render job was successful */
    success?: boolean;
    output?: StartRenderJobResponse.Output;
    /** Error that occurred during render */
    error?: string;
}

export namespace StartRenderJobResponse {
    /**
     * Type of output to be rendered
     */
    export type Target = "pdf" | "html" | "docx" | "xlsx" | "pptx" | "png" | "jpg";
    export const Target = {
        Pdf: "pdf",
        Html: "html",
        Docx: "docx",
        Xlsx: "xlsx",
        Pptx: "pptx",
        Png: "png",
        Jpg: "jpg",
    } as const;

    export interface Output {
        data: Output.Data;
        metadata: Output.Metadata;
    }

    export namespace Output {
        export interface Data {
            /** URL of the rendered output */
            url: string;
        }

        export interface Metadata {
            /** Time taken to render the output */
            renderTime: number;
        }
    }
}
