/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StartRenderJobResponse =
    | {
          jobId: string;
          templateId?: string | undefined;
          target: string;
          uploadPresignedS3Url?: string | undefined;
          formatOpts?:
              | {
                    fromPage?: number | undefined;
                    toPage?: number | undefined;
                    format?:
                        | ("letter" | "legal" | "tabloid" | "ledger" | "a0" | "a1" | "a2" | "a3" | "a4" | "a5" | "a6")
                        | undefined;
                    waitForSelector?: string | undefined;
                }
              | undefined;
          status?: string | undefined;
          success?: boolean | undefined;
          output?:
              | {
                    data: {
                        url: string;
                    };
                    metadata: {
                        renderTime: number;
                    };
                }
              | undefined;
          error?: string | undefined;
      }
    | {
          jobId: string;
      };
