/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Templates } from "./api/resources/templates/client/Client.js";
import { Documents } from "./api/resources/documents/client/Client.js";

export declare namespace PogodocApiClient {
    export interface Options {
        environment?: core.Supplier<environments.PogodocApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class PogodocApiClient {
    protected readonly _options: PogodocApiClient.Options;
    protected _templates: Templates | undefined;
    protected _documents: Documents | undefined;

    constructor(_options: PogodocApiClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get templates(): Templates {
        return (this._templates ??= new Templates(this._options));
    }

    public get documents(): Documents {
        return (this._documents ??= new Documents(this._options));
    }
}
