/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Templates } from "./api/resources/templates/client/Client";
import { Documents } from "./api/resources/documents/client/Client";
import { Tokens } from "./api/resources/tokens/client/Client";

export declare namespace PogodocApiClient {
    export interface Options {
        environment?: core.Supplier<environments.PogodocApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class PogodocApiClient {
    protected _templates: Templates | undefined;
    protected _documents: Documents | undefined;
    protected _tokens: Tokens | undefined;

    constructor(protected readonly _options: PogodocApiClient.Options) {}

    public get templates(): Templates {
        return (this._templates ??= new Templates(this._options));
    }

    public get documents(): Documents {
        return (this._documents ??= new Documents(this._options));
    }

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this._options));
    }
}
