/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PogodocApiEnvironment = {
    Default: "https://api.pogodoc.com/v1",
} as const;

export type PogodocApiEnvironment = typeof PogodocApiEnvironment.Default;
