/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index";

/**
 * @example
 *     {
 *         templateId: "templateId",
 *         type: "docx",
 *         data: {
 *             "key": "value"
 *         }
 *     }
 */
export interface GenerateDocumentPreviewRequest {
    templateId: string;
    type: PogodocApi.GenerateDocumentPreviewRequestType;
    data: Record<string, unknown>;
    formatOpts?: PogodocApi.GenerateDocumentPreviewRequestFormatOpts;
}
