/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { GenerateDocumentPreviewRequestFormatOptsFormat } from "./GenerateDocumentPreviewRequestFormatOptsFormat";

export const GenerateDocumentPreviewRequestFormatOpts: core.serialization.ObjectSchema<
    serializers.GenerateDocumentPreviewRequestFormatOpts.Raw,
    PogodocApi.GenerateDocumentPreviewRequestFormatOpts
> = core.serialization.object({
    fromPage: core.serialization.number().optional(),
    toPage: core.serialization.number().optional(),
    format: GenerateDocumentPreviewRequestFormatOptsFormat.optional(),
    waitForSelector: core.serialization.string().optional(),
});

export declare namespace GenerateDocumentPreviewRequestFormatOpts {
    export interface Raw {
        fromPage?: number | null;
        toPage?: number | null;
        format?: GenerateDocumentPreviewRequestFormatOptsFormat.Raw | null;
        waitForSelector?: string | null;
    }
}
