/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetJobStatusResponseOutputMetadata: core.serialization.ObjectSchema<
    serializers.GetJobStatusResponseOutputMetadata.Raw,
    PogodocApi.GetJobStatusResponseOutputMetadata
> = core.serialization.object({
    renderTime: core.serialization.number(),
});

export declare namespace GetJobStatusResponseOutputMetadata {
    export interface Raw {
        renderTime: number;
    }
}
