/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { GetJobStatusResponseOutputData } from "./GetJobStatusResponseOutputData";
import { GetJobStatusResponseOutputMetadata } from "./GetJobStatusResponseOutputMetadata";

export const GetJobStatusResponseOutput: core.serialization.ObjectSchema<
    serializers.GetJobStatusResponseOutput.Raw,
    PogodocApi.GetJobStatusResponseOutput
> = core.serialization.object({
    data: GetJobStatusResponseOutputData,
    metadata: GetJobStatusResponseOutputMetadata,
});

export declare namespace GetJobStatusResponseOutput {
    export interface Raw {
        data: GetJobStatusResponseOutputData.Raw;
        metadata: GetJobStatusResponseOutputMetadata.Raw;
    }
}
