/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const StartRenderJobResponse: core.serialization.ObjectSchema<
    serializers.StartRenderJobResponse.Raw,
    PogodocApi.StartRenderJobResponse
> = core.serialization.object({
    jobId: core.serialization.string(),
});

export declare namespace StartRenderJobResponse {
    export interface Raw {
        jobId: string;
    }
}
