/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { StartImmediateRenderRequestFormatOptsFormat } from "./StartImmediateRenderRequestFormatOptsFormat";

export const StartImmediateRenderRequestFormatOpts: core.serialization.ObjectSchema<
    serializers.StartImmediateRenderRequestFormatOpts.Raw,
    PogodocApi.StartImmediateRenderRequestFormatOpts
> = core.serialization.object({
    fromPage: core.serialization.number().optional(),
    toPage: core.serialization.number().optional(),
    format: StartImmediateRenderRequestFormatOptsFormat.optional(),
    waitForSelector: core.serialization.string().optional(),
});

export declare namespace StartImmediateRenderRequestFormatOpts {
    export interface Raw {
        fromPage?: number | null;
        toPage?: number | null;
        format?: StartImmediateRenderRequestFormatOptsFormat.Raw | null;
        waitForSelector?: string | null;
    }
}
