/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GenerateTemplatePreviewsResponse {
    pngPreview: GenerateTemplatePreviewsResponse.PngPreview;
    pdfPreview: GenerateTemplatePreviewsResponse.PdfPreview;
}

export namespace GenerateTemplatePreviewsResponse {
    export interface PngPreview {
        /** URL of the rendered preview */
        url?: string;
        /** ID of the render job */
        jobId: string;
    }

    export interface PdfPreview {
        /** URL of the rendered preview */
        url?: string;
        /** ID of the render job */
        jobId: string;
    }
}
