/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface SaveCreatedTemplateRequestTemplateInfo {
    title: string;
    description: string;
    type: PogodocApi.SaveCreatedTemplateRequestTemplateInfoType;
    sampleData: Record<string, unknown>;
    sourceCode?: string;
    categories: PogodocApi.SaveCreatedTemplateRequestTemplateInfoCategoriesItem[];
}
