/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { GenerateTemplatePreviewsRequestFormatOptsFormat } from "./GenerateTemplatePreviewsRequestFormatOptsFormat";

export const GenerateTemplatePreviewsRequestFormatOpts: core.serialization.ObjectSchema<
    serializers.GenerateTemplatePreviewsRequestFormatOpts.Raw,
    PogodocApi.GenerateTemplatePreviewsRequestFormatOpts
> = core.serialization.object({
    fromPage: core.serialization.number().optional(),
    toPage: core.serialization.number().optional(),
    format: GenerateTemplatePreviewsRequestFormatOptsFormat.optional(),
    waitForSelector: core.serialization.string().optional(),
});

export declare namespace GenerateTemplatePreviewsRequestFormatOpts {
    export interface Raw {
        fromPage?: number | null;
        toPage?: number | null;
        format?: GenerateTemplatePreviewsRequestFormatOptsFormat.Raw | null;
        waitForSelector?: string | null;
    }
}
