/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const GeneratePresignedGetUrlResponse: core.serialization.ObjectSchema<
    serializers.GeneratePresignedGetUrlResponse.Raw,
    PogodocApi.GeneratePresignedGetUrlResponse
> = core.serialization.object({
    presignedUrl: core.serialization.string(),
});

export declare namespace GeneratePresignedGetUrlResponse {
    export interface Raw {
        presignedUrl: string;
    }
}
