/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetTemplateIndexHtmlResponse: core.serialization.ObjectSchema<
    serializers.GetTemplateIndexHtmlResponse.Raw,
    PogodocApi.GetTemplateIndexHtmlResponse
> = core.serialization.object({
    templateIndex: core.serialization.string(),
});

export declare namespace GetTemplateIndexHtmlResponse {
    export interface Raw {
        templateIndex: string;
    }
}
