/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const SaveCreatedTemplateRequestTemplateInfoCategoriesItem: core.serialization.Schema<
    serializers.SaveCreatedTemplateRequestTemplateInfoCategoriesItem.Raw,
    PogodocApi.SaveCreatedTemplateRequestTemplateInfoCategoriesItem
> = core.serialization.enum_(["invoice", "mail", "report", "cv", "other"]);

export declare namespace SaveCreatedTemplateRequestTemplateInfoCategoriesItem {
    export type Raw = "invoice" | "mail" | "report" | "cv" | "other";
}
