/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const SaveCreatedTemplateRequestPreviewIds: core.serialization.ObjectSchema<
    serializers.SaveCreatedTemplateRequestPreviewIds.Raw,
    PogodocApi.SaveCreatedTemplateRequestPreviewIds
> = core.serialization.object({
    pngJobId: core.serialization.string(),
    pdfJobId: core.serialization.string(),
});

export declare namespace SaveCreatedTemplateRequestPreviewIds {
    export interface Raw {
        pngJobId: string;
        pdfJobId: string;
    }
}
