/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { SaveCreatedTemplateRequestTemplateInfoType } from "./SaveCreatedTemplateRequestTemplateInfoType";
import { SaveCreatedTemplateRequestTemplateInfoCategoriesItem } from "./SaveCreatedTemplateRequestTemplateInfoCategoriesItem";

export const SaveCreatedTemplateRequestTemplateInfo: core.serialization.ObjectSchema<
    serializers.SaveCreatedTemplateRequestTemplateInfo.Raw,
    PogodocApi.SaveCreatedTemplateRequestTemplateInfo
> = core.serialization.object({
    title: core.serialization.string(),
    description: core.serialization.string(),
    type: SaveCreatedTemplateRequestTemplateInfoType,
    sampleData: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    sourceCode: core.serialization.string().optional(),
    categories: core.serialization.list(SaveCreatedTemplateRequestTemplateInfoCategoriesItem),
});

export declare namespace SaveCreatedTemplateRequestTemplateInfo {
    export interface Raw {
        title: string;
        description: string;
        type: SaveCreatedTemplateRequestTemplateInfoType.Raw;
        sampleData: Record<string, unknown>;
        sourceCode?: string | null;
        categories: SaveCreatedTemplateRequestTemplateInfoCategoriesItem.Raw[];
    }
}
