/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateTemplateRequestTemplateInfoCategoriesItem: core.serialization.Schema<
    serializers.UpdateTemplateRequestTemplateInfoCategoriesItem.Raw,
    PogodocApi.UpdateTemplateRequestTemplateInfoCategoriesItem
> = core.serialization.enum_(["invoice", "mail", "report", "cv", "other"]);

export declare namespace UpdateTemplateRequestTemplateInfoCategoriesItem {
    export type Raw = "invoice" | "mail" | "report" | "cv" | "other";
}
