/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateTemplateResponse: core.serialization.ObjectSchema<
    serializers.UpdateTemplateResponse.Raw,
    PogodocApi.UpdateTemplateResponse
> = core.serialization.object({
    newContentId: core.serialization.string(),
});

export declare namespace UpdateTemplateResponse {
    export interface Raw {
        newContentId: string;
    }
}
