/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as PogodocApi from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateTemplateRequestTemplateInfoType } from "./UpdateTemplateRequestTemplateInfoType";
import { UpdateTemplateRequestTemplateInfoCategoriesItem } from "./UpdateTemplateRequestTemplateInfoCategoriesItem";

export const UpdateTemplateRequestTemplateInfo: core.serialization.ObjectSchema<
    serializers.UpdateTemplateRequestTemplateInfo.Raw,
    PogodocApi.UpdateTemplateRequestTemplateInfo
> = core.serialization.object({
    title: core.serialization.string(),
    description: core.serialization.string(),
    type: UpdateTemplateRequestTemplateInfoType,
    sampleData: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    sourceCode: core.serialization.string().optional(),
    categories: core.serialization.list(UpdateTemplateRequestTemplateInfoCategoriesItem),
});

export declare namespace UpdateTemplateRequestTemplateInfo {
    export interface Raw {
        title: string;
        description: string;
        type: UpdateTemplateRequestTemplateInfoType.Raw;
        sampleData: Record<string, unknown>;
        sourceCode?: string | null;
        categories: UpdateTemplateRequestTemplateInfoCategoriesItem.Raw[];
    }
}
