/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InitializeRenderJobResponseTarget = "pdf" | "html" | "docx" | "xlsx" | "pptx" | "png" | "jpg";
export const InitializeRenderJobResponseTarget = {
    Pdf: "pdf",
    Html: "html",
    Docx: "docx",
    Xlsx: "xlsx",
    Pptx: "pptx",
    Png: "png",
    Jpg: "jpg",
} as const;
