/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         indexHtml: "indexHtml"
 *     }
 */
export interface UploadTemplateIndexHtmlRequest {
    /** New index.html file of the template */
    indexHtml: string;
}
