/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as PogodocApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { InitializeRenderJobRequestType } from "../../types/InitializeRenderJobRequestType";
import { InitializeRenderJobRequestTarget } from "../../types/InitializeRenderJobRequestTarget";
import { InitializeRenderJobRequestFormatOpts } from "../../types/InitializeRenderJobRequestFormatOpts";

export const InitializeRenderJobRequest: core.serialization.Schema<
    serializers.InitializeRenderJobRequest.Raw,
    PogodocApi.InitializeRenderJobRequest
> = core.serialization.object({
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    type: InitializeRenderJobRequestType,
    target: InitializeRenderJobRequestTarget,
    templateId: core.serialization.string().optional(),
    formatOpts: InitializeRenderJobRequestFormatOpts.optional(),
});

export declare namespace InitializeRenderJobRequest {
    export interface Raw {
        data?: Record<string, unknown> | null;
        type: InitializeRenderJobRequestType.Raw;
        target: InitializeRenderJobRequestTarget.Raw;
        templateId?: string | null;
        formatOpts?: InitializeRenderJobRequestFormatOpts.Raw | null;
    }
}
