/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as PogodocApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.js";

export declare namespace Documents {
    export interface Options {
        environment?: core.Supplier<environments.PogodocApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Documents {
    protected readonly _options: Documents.Options;

    constructor(_options: Documents.Options) {
        this._options = _options;
    }

    /**
     * Creates a new render job with a unique ID, sets up S3 storage for template and data files, and generates presigned upload URLs if needed. Requires subscription check.
     *
     * @param {PogodocApi.InitializeRenderJobRequest} request
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.documents.initializeRenderJob({
     *         type: "docx",
     *         target: "pdf"
     *     })
     */
    public initializeRenderJob(
        request: PogodocApi.InitializeRenderJobRequest,
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<PogodocApi.InitializeRenderJobResponse> {
        return core.HttpResponsePromise.fromPromise(this.__initializeRenderJob(request, requestOptions));
    }

    private async __initializeRenderJob(
        request: PogodocApi.InitializeRenderJobRequest,
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<PogodocApi.InitializeRenderJobResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PogodocApiEnvironment.Default,
                "documents/init",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as PogodocApi.InitializeRenderJobResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PogodocApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PogodocApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PogodocApiTimeoutError("Timeout exceeded when calling POST /documents/init.");
            case "unknown":
                throw new errors.PogodocApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Takes a previously initialized job, updates its status to in-progress, and triggers the rendering process using Puppeteer. Can optionally wait for render completion.
     *
     * @param {string} jobId
     * @param {PogodocApi.StartRenderJobRequest} request
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.documents.startRenderJob("jobId")
     */
    public startRenderJob(
        jobId: string,
        request: PogodocApi.StartRenderJobRequest = {},
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<PogodocApi.StartRenderJobResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startRenderJob(jobId, request, requestOptions));
    }

    private async __startRenderJob(
        jobId: string,
        request: PogodocApi.StartRenderJobRequest = {},
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<PogodocApi.StartRenderJobResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PogodocApiEnvironment.Default,
                `documents/${encodeURIComponent(jobId)}/render`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PogodocApi.StartRenderJobResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PogodocApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PogodocApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PogodocApiTimeoutError(
                    "Timeout exceeded when calling POST /documents/{jobId}/render.",
                );
            case "unknown":
                throw new errors.PogodocApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Combines initialization and rendering in one step. Creates a job, uploads template/data directly, starts rendering, and adds the document to Strapi. Requires subscription check.
     *
     * @param {PogodocApi.StartImmediateRenderRequest} request
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.documents.startImmediateRender({
     *         type: "docx",
     *         target: "pdf",
     *         data: {
     *             "key": "value"
     *         }
     *     })
     */
    public startImmediateRender(
        request: PogodocApi.StartImmediateRenderRequest,
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<PogodocApi.StartImmediateRenderResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startImmediateRender(request, requestOptions));
    }

    private async __startImmediateRender(
        request: PogodocApi.StartImmediateRenderRequest,
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<PogodocApi.StartImmediateRenderResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PogodocApiEnvironment.Default,
                "documents/immediate-render",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as PogodocApi.StartImmediateRenderResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PogodocApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PogodocApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PogodocApiTimeoutError(
                    "Timeout exceeded when calling POST /documents/immediate-render.",
                );
            case "unknown":
                throw new errors.PogodocApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetches detailed job information from S3 storage including job status, template ID, target format, and output details if available.
     *
     * @param {string} jobId - ID of the render job
     * @param {Documents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.documents.getJobStatus("jobId")
     */
    public getJobStatus(
        jobId: string,
        requestOptions?: Documents.RequestOptions,
    ): core.HttpResponsePromise<PogodocApi.GetJobStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getJobStatus(jobId, requestOptions));
    }

    private async __getJobStatus(
        jobId: string,
        requestOptions?: Documents.RequestOptions,
    ): Promise<core.WithRawResponse<PogodocApi.GetJobStatusResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PogodocApiEnvironment.Default,
                `jobs/${encodeURIComponent(jobId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as PogodocApi.GetJobStatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PogodocApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PogodocApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PogodocApiTimeoutError("Timeout exceeded when calling GET /jobs/{jobId}.");
            case "unknown":
                throw new errors.PogodocApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
