/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetUserTemplatesRequest {
    /**
     * Category of the template
     */
    category?: PogodocApi.GetUserTemplatesRequestCategory;
    /**
     * Search by title or description
     */
    search?: string;
    /**
     * Type of template to be rendered
     */
    type?: PogodocApi.GetUserTemplatesRequestType;
    /**
     * Sort order
     */
    sort?: PogodocApi.GetUserTemplatesRequestSort;
}
