/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         templateInfo: {
 *             title: "title",
 *             description: "description",
 *             type: "docx",
 *             sampleData: {
 *                 "key": "value"
 *             },
 *             categories: ["invoice"]
 *         },
 *         previewIds: {
 *             pngJobId: "pngJobId",
 *             pdfJobId: "pdfJobId"
 *         }
 *     }
 */
export interface SaveCreatedTemplateRequest {
    templateInfo: SaveCreatedTemplateRequest.TemplateInfo;
    previewIds: SaveCreatedTemplateRequest.PreviewIds;
}

export namespace SaveCreatedTemplateRequest {
    export interface TemplateInfo {
        /** Title of the template */
        title: string;
        /** Description of the template */
        description: string;
        /** Type of template to be rendered */
        type: TemplateInfo.Type;
        /** Sample data for the template */
        sampleData: Record<string, unknown>;
        sourceCode?: string;
        /** Categories of the template */
        categories: TemplateInfo.Categories.Item[];
        orientation?: TemplateInfo.Orientation;
        dimensions?: TemplateInfo.Dimensions;
    }

    export namespace TemplateInfo {
        /**
         * Type of template to be rendered
         */
        export type Type = "docx" | "xlsx" | "pptx" | "ejs" | "html" | "latex" | "react";
        export const Type = {
            Docx: "docx",
            Xlsx: "xlsx",
            Pptx: "pptx",
            Ejs: "ejs",
            Html: "html",
            Latex: "latex",
            React: "react",
        } as const;
        export type Categories = Categories.Item[];

        export namespace Categories {
            /**
             * Category of the template
             */
            export type Item =
                | "invoice"
                | "mail"
                | "report"
                | "cv"
                | "receipt"
                | "order"
                | "contract"
                | "certificate"
                | "statement"
                | "brochure"
                | "warranty"
                | "poster"
                | "menu"
                | "catalog"
                | "packaging"
                | "advertisement"
                | "other"
                | "favorite";
            export const Item = {
                Invoice: "invoice",
                Mail: "mail",
                Report: "report",
                Cv: "cv",
                Receipt: "receipt",
                Order: "order",
                Contract: "contract",
                Certificate: "certificate",
                Statement: "statement",
                Brochure: "brochure",
                Warranty: "warranty",
                Poster: "poster",
                Menu: "menu",
                Catalog: "catalog",
                Packaging: "packaging",
                Advertisement: "advertisement",
                Other: "other",
                Favorite: "favorite",
            } as const;
        }

        export type Orientation = "landscape" | "portrait";
        export const Orientation = {
            Landscape: "landscape",
            Portrait: "portrait",
        } as const;

        export interface Dimensions {
            width: number;
            height: number;
        }
    }

    export interface PreviewIds {
        /** ID of the job for the PNG preview */
        pngJobId: string;
        /** ID of the job for the PDF preview */
        pdfJobId: string;
    }
}
