/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface GenerateDocumentPreviewRequestFormatOpts {
    fromPage?: number;
    toPage?: number;
    format?: PogodocApi.GenerateDocumentPreviewRequestFormatOptsFormat;
    waitForSelector?: string;
}
