/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type InitializeRenderJobRequestFormatOptsFormat =
    | "letter"
    | "legal"
    | "tabloid"
    | "ledger"
    | "a0"
    | "a1"
    | "a2"
    | "a3"
    | "a4"
    | "a5"
    | "a6";
export const InitializeRenderJobRequestFormatOptsFormat = {
    Letter: "letter",
    Legal: "legal",
    Tabloid: "tabloid",
    Ledger: "ledger",
    A0: "a0",
    A1: "a1",
    A2: "a2",
    A3: "a3",
    A4: "a4",
    A5: "a5",
    A6: "a6",
} as const;
