/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../../index";

/**
 * @example
 *     {
 *         startImmediateRenderRequestData: {
 *             "key": "value"
 *         },
 *         type: "docx",
 *         target: "pdf"
 *     }
 */
export interface StartImmediateRenderRequest {
    startImmediateRenderRequestData: Record<string, unknown>;
    type: PogodocApi.StartImmediateRenderRequestType;
    target: PogodocApi.StartImmediateRenderRequestTarget;
    templateId?: string;
    formatOpts?: PogodocApi.StartImmediateRenderRequestFormatOpts;
    template?: string;
}
