/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface GetJobStatusResponseOutput {
    data: PogodocApi.GetJobStatusResponseOutputData;
    metadata: PogodocApi.GetJobStatusResponseOutputMetadata;
}
