/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as PogodocApi from "../../../index";

export interface GetJobStatusResponse {
    type: PogodocApi.GetJobStatusResponseType;
    jobId: string;
    target: PogodocApi.GetJobStatusResponseTarget;
    output?: PogodocApi.GetJobStatusResponseOutput;
    success?: boolean;
    status?: string;
}
